create table shops (
  id bigint generated by default as identity primary key,
  domain text,
  ecommerce_platform text,
  logo text,
  monthly_traffic text,
  alexa_url_info_rank text,
  product_count bigint,
  collection_count bigint,
  domain_register_date text,
  first_backlink_date text,
  backlink_count bigint,
  dead_or_alive boolean,
  company_name text,
  ecommerce_categories text,
  blog_count bigint,
  inserted_at timestamp with time zone default timezone('utc' :: text, now()) not null,
  updated_at timestamp with time zone default timezone('utc' :: text, now()) not null
);

create table shop_sitemaps (
  id bigint generated by default as identity primary key,
  domain text,
  shopid bigint,
  loc text,
  lastmod text,
  sitemap text,
  etag text,
  sitemap_last_modified text,
  sitemap_size_mb text,
  download_date text,
  inserted_at timestamp with time zone default timezone('utc' :: text, now()) not null,
  updated_at timestamp with time zone default timezone('utc' :: text, now()) not null
);

create table shop_crawls (
  id bigint generated by default as identity primary key,
  domain text,
  shopid bigint,
  crawl_url text,
  crawl_url_status text,
  crawl_time text,
  change_last_maded text,
  inserted_at timestamp with time zone default timezone('utc' :: text, now()) not null,
  updated_at timestamp with time zone default timezone('utc' :: text, now()) not null
);